[package]
name = "preon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preon_core = { path = "../preon_core" }
preon_renderer_opengl = { path = "../preon_renderer_opengl" }