[package]
name = "preon_engine"
version = "0.1.0"
edition = "2021"

[features]
default = ["logging"]
debug = []
logging = ["log"]
std = []

[dependencies]
log = { version = "0.4.17", optional = true }
libm = "0.2.5"