[package]
name = "preon_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.2"
winit = "0.26"
wgpu = "0.12"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"