[package]
name = "preon_data"
version = "1.0.0"
edition = "2018"
readme = "./README.md"
license = "MIT"
authors = [ "Hugo van de Kuilen from Hugo4IT" ]
repository = "https://github.com/Hugo4IT/PreonData"
categories = [ "nostd", "data", "serialization", "deserialization", "bytes" ]