[package]
name = "demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preon = { path = "../preon" }
preon_renderer_wgpu = { path = "../preon_renderer_wgpu" }