[package]
name = "preon_module_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
preon_engine = { path = "../preon_engine" }
quick-xml = "0.22.0"
log = "0.4.14"

[dev-dependencies]
preon_module_wgpu = { path = "../preon_module_wgpu" }
env_logger = "0.9.0"
